language: python
python:
  - 2.7
  - 3.5
  - 3.6
os:
  - linux
addons:
  apt:
    packages:
      - libhmsbeagle1v5
      - libhmsbeagle-dev
before_install:
  - export CPLUS_INCLUDE_PATH=/usr/include/libhmsbeagle
install:
  - pip install ".[test]" .
script: pytest