language: minimal

services:
  - docker

script:
  - docker run -v ${PWD}:/beaglepy -t 4ment/beaglepy /bin/bash -c "pip install .[test] && pytest"
  - docker run -v ${PWD}:/beaglepy -t 4ment/beaglepy /bin/bash -c "pip3 install .[test] && pytest"